import { movieType } from 'src/app/models/model';

export const sampleMovie = {
  adult: false,
  backdropImage:
    'https://image.tmdb.org/t/p/original/5gPQKfFJnl8d1edbkOzKONo4mnr.jpg',
  id: 76600,
  languages: 'en',
  popularity: 5332.225,
  posterImage:
    'https://image.tmdb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
  release_date: '2022-12-14',
  title: 'Avatar: The Way of Water',
  vote_average: 7.7,
  vote_count: 3497,
  type: movieType.Movie,
};

// GET: https://api.themoviedb.org/3/movie/76600?api_key=ccca420ee41f1022a903c341a3fa53c6&language=en-US
export const sampleMovieDetail = {
  adult: false,
  backdropImage:
    'https://image.tmdb.org/t/p/original/5gPQKfFJnl8d1edbkOzKONo4mnr.jpg',
  genres: [
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 28,
      name: 'Action',
    },
  ],
  homepage: 'https://www.avatar.com/movies/avatar-the-way-of-water',
  id: 76600,
  language: 'en',
  title: 'Avatar: The Way of Water',
  overview:
    'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
  popularity: 5332.225,
  productions: [
    {
      id: 574,
      logo_path:
        'https://image.tmdb.org/t/p/original/iB6GjNVHs5hOqcEYt2rcjBqIjki.png',
      name: 'Lightstorm Entertainment',
      origin_country: 'US',
    },
    {
      id: 127928,
      logo_path:
        'https://image.tmdb.org/t/p/original/cxMxGzAgMMBhTXkcpYYCxWCOY90.png',
      name: '20th Century Studios',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2022-12-14',
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Return to Pandora.',
  video: false,
  vote_average: 7.7,
  vote_count: 3531,
};

// GET https://api.themoviedb.org/3/movie/76600/recommendations?api_key=ccca420ee41f1022a903c341a3fa53c6&language=en-US&page=1

export const recommendationsMovie = [
  {
    adult: false,
    backdropImage:
      'https://image.tmdb.org/t/p/original/c1bz69r0v065TGFA5nqBiKzPDys.jpg',
    id: 830784,
    title: 'Lyle, Lyle, Crocodile',
    language: 'en',
    // "overview": "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
    posterImage:
      'https://image.tmdb.org/t/p/original/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg',

    popularity: 526.877,
    release_date: '2022-10-07',
    vote_average: 7.69,
    vote_count: 239,
  },
  {
    adult: false,
    backdropImage:
      'https://image.tmdb.org/t/p/original/2Ft4xmWa1Edgj2P1OYmoSAoYRqz.jpg',
    id: 663712,
    title: 'Terrifier 2',
    language: 'en',
    posterImage:
      'https://image.tmdb.org/t/p/original/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg',
    popularity: 826.014,
    release_date: '2022-10-06',
    vote_average: 6.993,
    vote_count: 837,
  },
  {
    adult: false,
    backdropImage:
      'https://image.tmdb.org/t/p/original/rpZFknesBbZL4uqESFcJ0aTnBo5.jpg',
    id: 676701,
    title: 'Tad, the Lost Explorer and the Emerald Tablet',
    language: 'es',
    // overview: "Tad accidentally unleashes an ancient spell, endangering the lives of his friends Mummy, Jeff, and Belzoni. With everyone against him and only helped by Sara, he sets off on an adventure to end the Curse of the Mummy.",
    posterImage:
      'https://image.tmdb.org/t/p/original/eEWi0ptaVSwLUs84rhZjtNIhgbp.jpg',
    popularity: 334.289,
    release_date: '2022-08-24',
    vote_average: 7.793,
    vote_count: 176,
  },
  {
    adult: false,
    backdropImage:
      'https://image.tmdb.org/t/p/original/au4HUSWDRadIcl9CqySlw1kJMfo.jpg',
    id: 829799,
    title: 'Paradise City',
    language: 'en',
    // overview: "Renegade bounty hunter Ryan Swan must carve his way through the Hawaiian crime world to wreak vengeance on the kingpin who murdered his father.",
    posterImage:
      'https://image.tmdb.org/t/p/original/xdmmd437QdjcCls8yCQxrH5YYM4.jpg',
    popularity: 452.896,
    release_date: '2022-11-11',
    vote_average: 5.716,
    vote_count: 51,
  },
  {
    adult: false,
    backdropImage:
      'https://image.tmdb.org/t/p/original/vNuHqmOJRQXY0PBd887DklSDlBP.jpg',
    id: 315162,
    title: 'Puss in Boots: The Last Wish',
    language: 'en',
    // overview: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    posterImage:
      'https://image.tmdb.org/t/p/original/lmf0zzR7ritjOL3qumRh3hfvOFK.jpg',

    popularity: 1397.696,
    release_date: '2022-12-07',
    vote_average: 7.989,
    vote_count: 181,
  },
];
export const sampleCast = {
  profilePath: 'profilePath',
  character: 'sample character',
  department: 'Actor',
  name: 'Song Ji Hyo',
  id: 13551,
};

export const sampleReview = {
  author: 'Vivy Vuong',
  content: 'This is a sample review',
  createdAt: new Date(),
  id: '231321',
  url: 'sampleurl',
};

export const sampleVideo = {
  id: '12121',
  name: 'Trailer',
  source: 'sampleSource',
  type: 'trailer',
  publishedAt: new Date(),
};

export const movieInfoFromAPI = {
  backdrop_path: '/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg',
  first_air_date: '2021-11-14',
  genre_ids: [18, 80],
  id: 97951,
  name: 'Mayor of Kingstown',
  origin_country: ['US'],
  original_language: 'en',
  original_name: 'Mayor of Kingstown',
  overview:
    'In a small Michigan town where the business of incarceration is the only thriving industry, the McClusky family are the power brokers between the police, criminals, inmates, prison guards and politicians in a city completely dependent on prisons and the prisoners they contain.',
  popularity: 837.363,
  poster_path: '/86OUOPulMiM8rjrQSt4KMev7UAa.jpg',
  vote_average: 8.2,
  vote_count: 139,
};

export const movieInfoFromAPIWithoutImage = {
  first_air_date: '2021-11-14',
  genre_ids: [18, 80],
  id: 97951,
  name: 'Mayor of Kingstown',
  origin_country: ['US'],
  original_language: 'en',
  original_name: 'Mayor of Kingstown',
  overview:
    'In a small Michigan town where the business of incarceration is the only thriving industry, the McClusky family are the power brokers between the police, criminals, inmates, prison guards and politicians in a city completely dependent on prisons and the prisoners they contain.',
  popularity: 837.363,
  vote_average: 8.2,
  vote_count: 139,
};

export const movieDetailFromApi = {
  adult: false,
  backdrop_path: '/x9McE1WFKnAHludiY7xfd7modDC.jpg',
  belongs_to_collection: null,
  budget: 4000000,
  genres: [
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 14,
      name: 'Fantasy',
    },
  ],
  homepage: '',
  id: 123,
  imdb_id: 'tt0077869',
  original_language: 'en',
  original_title: 'The Lord of the Rings',
  overview:
    "The Fellowship of the Ring embark on a journey to destroy the One Ring and end Sauron's reign over Middle-earth.",
  popularity: 26.485,
  poster_path: '/liW0mjvTyLs7UCumaHhx3PpU4VT.jpg',
  production_companies: [
    {
      id: 286,
      logo_path: null,
      name: 'Fantasy Films',
      origin_country: '',
    },
    {
      id: 4921,
      logo_path: null,
      name: 'Bakshi Productions',
      origin_country: '',
    },
    {
      id: 141322,
      logo_path: null,
      name: 'Saul Zaentz Film Productions',
      origin_country: '',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'ES',
      name: 'Spain',
    },
    {
      iso_3166_1: 'GB',
      name: 'United Kingdom',
    },
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '1978-11-15',
  revenue: 30471420,
  runtime: 132,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Fantasy...beyond your imagination',
  title: 'The Lord of the Rings',
  video: false,
  vote_average: 6.575,
  vote_count: 710,
};

export const tvshowDetailFromApi = {
  adult: false,
  backdrop_path: null,
  created_by: [],
  episode_run_time: [30],
  first_air_date: '2004-05-10',
  belongs_to_collection: {
    backdrop_path: '',
    poster_path: '',
  },
  genres: [
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 35,
      name: 'Comedy',
    },
  ],
  homepage: 'https://www.bbc.co.uk/programmes/p011fgk5',
  id: 100,
  in_production: false,
  languages: [],
  last_air_date: '2004-10-19',
  last_episode_to_air: {
    id: 4694,
    name: 'Money',
    overview: 'The animals begin to have problems with money.',
    vote_average: 0,
    vote_count: 0,
    air_date: '2004-10-19',
    episode_number: 3,
    production_code: '',
    runtime: 30,
    season_number: 1,
    show_id: 100,
    still_path: null,
  },
  name: 'I Am Not an Animal',
  next_episode_to_air: null,
  networks: [
    {
      id: 332,
      logo_path: '/6kl5tMuct7u3ej5myL4c9QQVSW1.png',
      name: 'BBC Two',
      origin_country: 'GB',
    },
  ],
  number_of_episodes: 6,
  number_of_seasons: 1,
  origin_country: ['GB'],
  original_language: 'en',
  original_name: 'I Am Not an Animal',
  overview:
    'I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.',
  popularity: 9.703,
  poster_path: '/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg',
  production_companies: [
    {
      id: 72930,
      logo_path: null,
      name: 'Baby Cow Animation',
      origin_country: 'GB',
    },
  ],
  production_countries: [],
  seasons: [
    {
      air_date: null,
      episode_count: 1,
      id: 299,
      name: 'Specials',
      overview: '',
      poster_path: null,
      season_number: 0,
    },
    {
      air_date: '2004-05-10',
      episode_count: 6,
      id: 298,
      name: 'Season 1',
      overview: '',
      poster_path: null,
      season_number: 1,
    },
  ],
  spoken_languages: [],
  status: 'Ended',
  tagline: '',
  type: 'Scripted',
  vote_average: 8.648,
  vote_count: 769,
};

export const castListFromAPI = {
  id: 123,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 16270,
      known_for_department: 'Acting',
      name: 'Christopher Guard',
      original_name: 'Christopher Guard',
      popularity: 1.875,
      profile_path: '/9fiBRqKot5xXngtjQGJq0CdZvYp.jpg',
      cast_id: 1,
      character: 'Frodo (voice)',
      credit_id: '52fe421bc3a36847f80047df',
      order: 0,
    },
    {
      adult: false,
      gender: 2,
      id: 16271,
      known_for_department: 'Acting',
      name: 'William Squire',
      original_name: 'William Squire',
      popularity: 1.551,
      profile_path: '/k3HPWslxIahGKovuQLgvk3CuB8i.jpg',
      cast_id: 2,
      character: 'Gandalf (voice)',
      credit_id: '52fe421bc3a36847f80047e3',
      order: 1,
    },
    {
      adult: false,
      gender: 0,
      id: 16272,
      known_for_department: 'Acting',
      name: 'Michael Scholes',
      original_name: 'Michael Scholes',
      popularity: 1.009,
      profile_path: '/rLeGxQU5hGGAJICFBE9ZBuizj4d.jpg',
      cast_id: 3,
      character: 'Sam (voice)',
      credit_id: '52fe421bc3a36847f80047e7',
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 5049,
      known_for_department: 'Acting',
      name: 'John Hurt',
      original_name: 'John Hurt',
      popularity: 17.186,
      profile_path: '/wGDGhBOggA8I2ktgc1QoHABEF0m.jpg',
      cast_id: 4,
      character: 'Aragorn (voice)',
      credit_id: '52fe421bc3a36847f80047eb',
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 16273,
      known_for_department: 'Acting',
      name: 'Simon Chandler',
      original_name: 'Simon Chandler',
      popularity: 4.645,
      profile_path: '/uqiDrIp84VEJY3vPCr95Cxp4mKY.jpg',
      cast_id: 5,
      character: 'Merry (voice)',
      credit_id: '52fe421bc3a36847f80047ef',
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 16274,
      known_for_department: 'Acting',
      name: 'Dominic Guard',
      original_name: 'Dominic Guard',
      popularity: 0.792,
      profile_path: '/nR90H8aL1CFi4FkofgfI5Shn2Zy.jpg',
      cast_id: 6,
      character: 'Pippin (voice)',
      credit_id: '52fe421bc3a36847f80047f3',
      order: 5,
    },
    {
      adult: false,
      gender: 2,
      id: 16275,
      known_for_department: 'Acting',
      name: 'Norman Bird',
      original_name: 'Norman Bird',
      popularity: 2.026,
      profile_path: '/gWimNB9CRJvE24vOeJbLpkxOi4q.jpg',
      cast_id: 7,
      character: 'Bilbo (voice)',
      credit_id: '52fe421bc3a36847f80047f7',
      order: 6,
    },
    {
      adult: false,
      gender: 2,
      id: 16380,
      known_for_department: 'Acting',
      name: 'Michael Graham Cox',
      original_name: 'Michael Graham Cox',
      popularity: 1.636,
      profile_path: '/oALXq1Y6wtdj3ArdmAwYRvAn5XX.jpg',
      cast_id: 8,
      character: 'Boromir (voice)',
      credit_id: '52fe421bc3a36847f80047fb',
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 6,
      known_for_department: 'Acting',
      name: 'Anthony Daniels',
      original_name: 'Anthony Daniels',
      popularity: 5.703,
      profile_path: '/7kR4kwXtvXtvrsxWeX3QLX5NS5V.jpg',
      cast_id: 9,
      character: 'Legolas (voice)',
      credit_id: '52fe421bc3a36847f80047ff',
      order: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 16381,
      known_for_department: 'Acting',
      name: 'David Buck',
      original_name: 'David Buck',
      popularity: 2.101,
      profile_path: '/ruU1fqPWT4lvaBTyrUlne1H2Dkz.jpg',
      cast_id: 10,
      character: 'Gimli (voice)',
      credit_id: '52fe421bc3a36847f8004803',
      order: 9,
    },
    {
      adult: false,
      gender: 2,
      id: 16382,
      known_for_department: 'Acting',
      name: 'Peter Woodthorpe',
      original_name: 'Peter Woodthorpe',
      popularity: 1.925,
      profile_path: '/lQyTZhDaW6p3lAb0aIKKGAiTmB6.jpg',
      cast_id: 11,
      character: 'Gollum (voice)',
      credit_id: '52fe421bc3a36847f8004807',
      order: 10,
    },
    {
      adult: false,
      gender: 0,
      id: 16383,
      known_for_department: 'Acting',
      name: 'Fraser Kerr',
      original_name: 'Fraser Kerr',
      popularity: 0.98,
      profile_path: null,
      cast_id: 12,
      character: 'Saruman (voice)',
      credit_id: '52fe421bc3a36847f800480b',
      order: 11,
    },
    {
      adult: false,
      gender: 2,
      id: 694,
      known_for_department: 'Acting',
      name: 'Philip Stone',
      original_name: 'Philip Stone',
      popularity: 5.46,
      profile_path: '/wKIz8L0TcKk26TNGj7rKfgP02UG.jpg',
      cast_id: 27,
      character: 'Theoden (voice)',
      credit_id: '595421379251412b2303e467',
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 10029,
      known_for_department: 'Acting',
      name: 'André Morell',
      original_name: 'André Morell',
      popularity: 5.453,
      profile_path: '/3YpAUiuLp9ZXL67W99W2XYdJ3se.jpg',
      cast_id: 13,
      character: 'Elrond (voice)',
      credit_id: '52fe421bc3a36847f800480f',
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 12828,
      known_for_department: 'Acting',
      name: 'Alan Tilvern',
      original_name: 'Alan Tilvern',
      popularity: 3.121,
      profile_path: '/6S1WHKzfLw02fFKjiN9LpvYM4XU.jpg',
      cast_id: 25,
      character: 'Innkeeper (voice)',
      credit_id: '595420b5c3a36814ae0439be',
      order: 14,
    },
    {
      adult: false,
      gender: 1,
      id: 55688,
      known_for_department: 'Acting',
      name: 'Annette Crosbie',
      original_name: 'Annette Crosbie',
      popularity: 4.364,
      profile_path: '/1ZuyTZbVJRfJ6HxxHL0XcL9GKYo.jpg',
      cast_id: 26,
      character: 'Galadriel (voice)',
      credit_id: '595420ccc3a36809c6040323',
      order: 15,
    },
    {
      adult: false,
      gender: 2,
      id: 111330,
      known_for_department: 'Acting',
      name: 'Michael Deacon',
      original_name: 'Michael Deacon',
      popularity: 1.4,
      profile_path: '/5LeisQk9otHLrAq0ymX8TTMMYT6.jpg',
      cast_id: 28,
      character: 'Wormtongue (voice)',
      credit_id: '595421989251412b31040a9f',
      order: 16,
    },
    {
      adult: false,
      gender: 2,
      id: 101512,
      known_for_department: 'Acting',
      name: 'John Westbrook',
      original_name: 'John Westbrook',
      popularity: 0.793,
      profile_path: '/552bAJ3wiZD2ASdOM7dbU06lJsC.jpg',
      cast_id: 29,
      character: 'Treebeard (voice)',
      credit_id: '595421a8c3a3683526022249',
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 12659,
      known_for_department: 'Acting',
      name: 'Billy Barty',
      original_name: 'Billy Barty',
      popularity: 7.357,
      profile_path: '/tsOruE36mrteBfVSFsegoJBSFQS.jpg',
      cast_id: 30,
      character: 'Character Actor (voice)',
      credit_id: '5b1bf71fc3a36848f20250e7',
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 127193,
      known_for_department: 'Acting',
      name: 'Jerry Maren',
      original_name: 'Jerry Maren',
      popularity: 3.156,
      profile_path: '/rgqSqrVkCsUpKccZ9gemgZIEiXZ.jpg',
      cast_id: 31,
      character: 'Character Actor (voice)',
      credit_id: '5b1bf7390e0a26764e0085d4',
      order: 19,
    },
    {
      adult: false,
      gender: 2,
      id: 114232,
      known_for_department: 'Acting',
      name: 'Chuck Hayward',
      original_name: 'Chuck Hayward',
      popularity: 6.183,
      profile_path: '/7Akk0i7GTJi7ViWAqt00sMZQfGo.jpg',
      cast_id: 32,
      character: 'Character Actor (voice)',
      credit_id: '5baeb42192514150f105c5ff',
      order: 20,
    },
    {
      adult: false,
      gender: 2,
      id: 18889,
      known_for_department: 'Crew',
      name: 'Mic Rodgers',
      original_name: 'Mic Rodgers',
      popularity: 2.16,
      profile_path: '/zGhWhiTfzeSzfKt9kK4Bk6ZS0xn.jpg',
      cast_id: 43,
      character: 'Character Actor (voice)',
      credit_id: '5fef3b95140bad003ca4f4e7',
      order: 21,
    },
    {
      adult: false,
      gender: 2,
      id: 141450,
      known_for_department: 'Acting',
      name: 'Mel Smith',
      original_name: 'Mel Smith',
      popularity: 4.661,
      profile_path: '/vynnJ4jWZvGRClXTN4kFQqTEIdn.jpg',
      cast_id: 44,
      character: 'Character Actor',
      credit_id: '61df63372811a10019b5e491',
      order: 22,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 1310,
      known_for_department: 'Production',
      name: 'Saul Zaentz',
      original_name: 'Saul Zaentz',
      popularity: 0.652,
      profile_path: null,
      credit_id: '52fe421bc3a36847f8004833',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      gender: 2,
      id: 129,
      known_for_department: 'Writing',
      name: 'J.R.R. Tolkien',
      original_name: 'J.R.R. Tolkien',
      popularity: 3.074,
      profile_path: '/8AYNNfNuhpzPHxki7cBISG9JpGx.jpg',
      credit_id: '52fe421bc3a36847f800481b',
      department: 'Writing',
      job: 'Novel',
    },
    {
      adult: false,
      gender: 2,
      id: 16384,
      known_for_department: 'Directing',
      name: 'Ralph Bakshi',
      original_name: 'Ralph Bakshi',
      popularity: 1.975,
      profile_path: '/qnEd6krjpW9blCNA90iw0AR58dR.jpg',
      credit_id: '52fe421bc3a36847f8004815',
      department: 'Directing',
      job: 'Director',
    },
    {
      adult: false,
      gender: 0,
      id: 16385,
      known_for_department: 'Writing',
      name: 'Chris Conkling',
      original_name: 'Chris Conkling',
      popularity: 0.6,
      profile_path: null,
      credit_id: '52fe421bc3a36847f8004821',
      department: 'Writing',
      job: 'Screenplay',
    },
    {
      adult: false,
      gender: 2,
      id: 16386,
      known_for_department: 'Writing',
      name: 'Peter S. Beagle',
      original_name: 'Peter S. Beagle',
      popularity: 0.98,
      profile_path: null,
      credit_id: '52fe421bc3a36847f8004827',
      department: 'Writing',
      job: 'Screenplay',
    },
    {
      adult: false,
      gender: 0,
      id: 16387,
      known_for_department: 'Production',
      name: 'Nancy Eichler',
      original_name: 'Nancy Eichler',
      popularity: 0.6,
      profile_path: null,
      credit_id: '52fe421bc3a36847f800482d',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      gender: 2,
      id: 2027,
      known_for_department: 'Sound',
      name: 'Leonard Rosenman',
      original_name: 'Leonard Rosenman',
      popularity: 0.6,
      profile_path: '/f3hxgLgST2hfFkjkiP9hdCcWkj9.jpg',
      credit_id: '52fe421bc3a36847f8004839',
      department: 'Sound',
      job: 'Original Music Composer',
    },
    {
      adult: false,
      gender: 2,
      id: 16389,
      known_for_department: 'Directing',
      name: 'Timothy Galfas',
      original_name: 'Timothy Galfas',
      popularity: 0.98,
      profile_path: null,
      credit_id: '52fe421bc3a36847f800483f',
      department: 'Camera',
      job: 'Director of Photography',
    },
    {
      adult: false,
      gender: 2,
      id: 16390,
      known_for_department: 'Editing',
      name: 'Donald W. Ernst',
      original_name: 'Donald W. Ernst',
      popularity: 0.6,
      profile_path: null,
      credit_id: '52fe421bc3a36847f8004845',
      department: 'Editing',
      job: 'Editor',
    },
    {
      adult: false,
      gender: 0,
      id: 12579,
      known_for_department: 'Camera',
      name: 'Phil Bray',
      original_name: 'Phil Bray',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ad9dcfdfc9f0038ae162e',
      department: 'Camera',
      job: 'Still Photographer',
    },
    {
      adult: false,
      gender: 2,
      id: 60250,
      known_for_department: 'Art',
      name: 'Barry E. Jackson',
      original_name: 'Barry E. Jackson',
      popularity: 0.6,
      profile_path: null,
      credit_id: '55614af1c3a3681f96000a59',
      department: 'Visual Effects',
      job: 'Animation Manager',
    },
    {
      adult: false,
      gender: 0,
      id: 1300919,
      known_for_department: 'Editing',
      name: 'Peter Kirby',
      original_name: 'Peter Kirby',
      popularity: 1.128,
      profile_path: null,
      credit_id: '5f7ad94f3429ff0038b68194',
      department: 'Editing',
      job: 'Editor',
    },
    {
      adult: false,
      gender: 0,
      id: 1447559,
      known_for_department: 'Visual Effects',
      name: 'Micki Zurcher',
      original_name: 'Micki Zurcher',
      popularity: 0.6,
      profile_path: null,
      credit_id: '553ad3c7925141651800bf86',
      department: 'Visual Effects',
      job: 'Animation Manager',
    },
    {
      adult: false,
      gender: 0,
      id: 1455558,
      known_for_department: 'Crew',
      name: 'Dale Baer',
      original_name: 'Dale Baer',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ada7c09191b00388ad6dc',
      department: 'Visual Effects',
      job: 'Key Animation',
    },
    {
      adult: false,
      gender: 0,
      id: 1989422,
      known_for_department: 'Sound',
      name: 'Dan Sharp',
      original_name: 'Dan Sharp',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ad9b5da10f000347a8b11',
      department: 'Sound',
      job: 'Assistant Sound Editor',
    },
    {
      adult: false,
      gender: 0,
      id: 2115777,
      known_for_department: 'Sound',
      name: 'Carl Lewis',
      original_name: 'Carl Lewis',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ad99a021cee00363a7707',
      department: 'Sound',
      job: 'Assistant Sound Editor',
    },
    {
      adult: false,
      gender: 0,
      id: 2803957,
      known_for_department: 'Directing',
      name: 'John Sparey',
      original_name: 'John Sparey',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ad974021cee00363a76f6',
      department: 'Directing',
      job: 'Assistant Director',
    },
    {
      adult: false,
      gender: 0,
      id: 2803962,
      known_for_department: 'Art',
      name: 'Marcia Adams',
      original_name: 'Marcia Adams',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ad9f4021cee00363a77c0',
      department: 'Art',
      job: 'Painter',
    },
    {
      adult: false,
      gender: 0,
      id: 2803963,
      known_for_department: 'Visual Effects',
      name: 'Christopher D. Andrews',
      original_name: 'Christopher D. Andrews',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ada19da10f000347a8be2',
      department: 'Visual Effects',
      job: 'Animation',
    },
    {
      adult: false,
      gender: 0,
      id: 2803964,
      known_for_department: 'Visual Effects',
      name: 'Craig Armstrong',
      original_name: 'Craig Armstrong',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ada53944a570037cf8560',
      department: 'Visual Effects',
      job: 'Key Animation',
    },
    {
      adult: false,
      gender: 0,
      id: 2803966,
      known_for_department: 'Visual Effects',
      name: 'Brenda Banks',
      original_name: 'Brenda Banks',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5f7ada933e2ec80037d4f242',
      department: 'Visual Effects',
      job: 'Key Animation',
    },
  ],
};

export const reviewListFromAPI = {
  author: 'Wuchak',
  author_details: {
    name: '',
    username: 'Wuchak',
    avatar_path: '/4KVM1VkqmXLOuwj1jjaSdxbvBDk.jpg',
    rating: 6.0,
  },
  content: '_**Amusing rural Mississippi odyssey in the 30s**',
  created_at: '2021-07-22T17:36:18.917Z',
  id: '60f9ac92fd140b00293ae1bf',
  updated_at: '2021-07-22T17:36:18.917Z',
  url: 'https://www.themoviedb.org/review/60f9ac92fd140b00293ae1bf',
};

export const sampleVideoFromAPI = {
  iso_639_1: 'en',
  iso_3166_1: 'US',
  name: 'Cord/Hide And Seek Trailer',
  key: 'L9Ph0kOe2vo',
  published_at: '2008-05-13T09:48:29.000Z',
  site: 'YouTube',
  size: 360,
  type: 'Trailer',
  official: false,
  id: '5bd427830e0a2622da013f31',
};
